# YAML corrigido para garantir que todos os campos sejam strings explícitas
# Este é o formato correto que deve estar no registry remoto
# URL: https://raw.githubusercontent.com/igorv43/hyperlane-registry/main/deployments/warp_routes/warpRouteConfigs.yaml

LUNC/terraclassictestnet-bsctestnet-sepolia-solanatestnet:
  tokens:
    - addressOrDenom: "terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml"
      chainName: "terraclassictestnet"
      standard: "CwHypCollateral"
      collateralAddressOrDenom: "uluna"
      connections:
        - token: "ethereum|bsctestnet|0x2144be4477202ba2d50c9a8be3181241878cf7d8"
        - token: "ethereum|sepolia|0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4"
        - token: "sealevel|solanatestnet|HNxN3ZSBtD5J2nNF4AATMhuvTWVeHQf18nTtzKtsnkyw"
      decimals: 6
      logoURI: "https://raw.githubusercontent.com/classic-terra/assets/60d34b97178cfdcd77fb87d7deeb7d3ab0ede6ee/icon/svg/LUNC.svg"
      name: "Luna Classic"
      symbol: "LUNC"
    - addressOrDenom: "0x2144be4477202ba2d50c9a8be3181241878cf7d8"
      chainName: "bsctestnet"
      standard: "EvmHypSynthetic"
      connections:
        - token: "cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml"
      decimals: 6
      logoURI: "https://raw.githubusercontent.com/classic-terra/assets/60d34b97178cfdcd77fb87d7deeb7d3ab0ede6ee/icon/svg/LUNC.svg"
      name: "Luna Classic"
      symbol: "wwwwLUNC"
    - addressOrDenom: "0x224a4419D7FA69D3bEbAbce574c7c84B48D829b4"
      chainName: "sepolia"
      standard: "EvmHypSynthetic"
      connections:
        - token: "cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml"
      decimals: 6
      logoURI: "https://raw.githubusercontent.com/classic-terra/assets/60d34b97178cfdcd77fb87d7deeb7d3ab0ede6ee/icon/svg/LUNC.svg"
      name: "Luna Classic"
      symbol: "LUNC"
    - addressOrDenom: "HNxN3ZSBtD5J2nNF4AATMhuvTWVeHQf18nTtzKtsnkyw"
      chainName: "solanatestnet"
      standard: "SealevelHypSynthetic"
      collateralAddressOrDenom: "3yhG9dDHVX6K1duf8znEcaJcuTiKSLYvfBD4xy6akxfu"
      connections:
        - token: "cosmos|terraclassictestnet|terra1zlm0h2xu6rhnjchn29hxnpvr74uxxqetar9y75zcehyx2mqezg9slj09ml"
      decimals: 6
      logoURI: "https://raw.githubusercontent.com/classic-terra/assets/60d34b97178cfdcd77fb87d7deeb7d3ab0ede6ee/icon/svg/LUNC.svg"
      name: "Luna Classic"
      symbol: "wwwwwLUNC"
  options: {}
